<?php

namespace ResteauBundle\Repository;

/**
 * CommandeDessertRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandeDessertRepository extends \Doctrine\ORM\EntityRepository
{
}
