<?php

namespace ResteauBundle\Repository;

/**
 * CommandeEntreeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandeEntreeRepository extends \Doctrine\ORM\EntityRepository
{
}
