<?php

namespace ResteauBundle\Repository;

/**
 * CommandesaladeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandesaladeRepository extends \Doctrine\ORM\EntityRepository
{
}
