<?php

namespace ResteauBundle\Repository;

/**
 * DessertRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DessertRepository extends \Doctrine\ORM\EntityRepository
{
}
